{{- range $name, $svc := .Values.services }}
apiVersion: v1
kind: Service
metadata:
  name: bezum-{{ $name }}
spec:
  type: ClusterIP
  selector:
    app: bezum-{{ $name }}
  ports:
    - port: {{ $svc.port }}
      targetPort: {{ $svc.port }}
---
{{- end }}
